modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory
license = "${license}"
issueTrackerURL="https://github.com/${github_user}/${mod_id_kebab}/issues" #optional
[[mods]] #mandatory
  modId = "${mod_id}" #mandatory
  version = "${mod_version}" #mandatory
  displayName = "${mod_title}" #mandatory
  updateJSONURL = "https://api.modrinth.com/updates/${mod_id_kebab}/forge_updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
  displayURL = "https://github.com/${github_user}/${mod_id_kebab}/tree/${minecraft_version}" #optional (displayed in the mod UI)
  logoFile = "banner.png" #optional
  credits = "${credits}" #optional
  authors = "${mod_authors}" #optional
  description = '''${description}''' #mandatory (Supports multiline text)
[[dependencies.${mod_id}]] #optional
  modId = "forge" #mandatory
  mandatory = true #mandatory
  versionRange = "${forge_loader_version_range}" #mandatory
  ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
  side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
  modId = "minecraft"
  mandatory = true
  versionRange = "${minecraft_version_range}"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.${mod_id}]]
  modId = "cobweb"
  mandatory = true
  versionRange = "[${cobweb_version},)"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.${mod_id}]]
  modId = "forgeconfigapiport"
  mandatory = true
  versionRange = "[${fcap_version},)"
  ordering = "NONE"
  side = "BOTH"
