# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 25
mod_version = 6.1.0
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Soul Fire'd
mod_id = soul_fire_d
mod_id_kebab = soul-fire-d
license = CNCLv1
description = Let Soul Fire burn!
credits =
github_user = crystal-nest
curseforge_id = 662413
minecraft_version = 26.1
minecraft_patch_version = .2
# https://minecraft.wiki/w/Pack_format#List_of_data_pack_formats
pack_format = 101.1
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 26.1.2-1

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.147.0+26.1.2
fabric_loader_version = 0.18.6

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 26.1.2.30-beta

# Dependencies
cobweb_version = 1.4.0
prometheus_version = 1.2.5

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
