# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 21
mod_version = 6.0.1
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Soul Fire'd
mod_id = soul_fire_d
mod_id_kebab = soul-fire-d
license = CNCLv1
description = Let Soul Fire burn!
credits =
github_user = crystal-nest
curseforge_id = 662413
minecraft_version = 1.21.6
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft = 1.21.6
parchment_version = 2025.06.29
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.6-20250617.151856

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.127.1+1.21.6
fabric_loader_version = 0.16.13

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 21.6.9-beta
neoforge_loader_version_range = [21.6,)

# Dependencies
cobweb_version = 1.4.0
prometheus_version = 1.1.2

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
