# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 21
mod_version = 5.1.6
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Soul Fire'd
mod_id = soul_fire_d
mod_id_kebab = soul-fire-d
license = CNCLv1
description = Let Soul Fire burn!
credits =
github_user = crystal-nest
curseforge_id = 662413
minecraft_version = 1.21.10
# https://minecraft.wiki/w/Pack_format#List_of_data_pack_formats
pack_format = 88
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft = 1.21.10
parchment_version = 2025.10.12
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.10-20251010.172816

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.135.0+1.21.10
fabric_loader_version = 0.17.2

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 21.10.10-beta
neoforge_loader_version_range = [21.10,)

# Dependencies
cobweb_version = 1.4.0
prometheus_version = 1.0.0

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
