---
name: Localization
about: File a new translation or a correction for an existing one
title: Death message localization for [lang-tag]
labels: localization
assignees: Nyphet

---

Language: english name of the language for which you want to provide a translation

Current translation: current translation for that language or "-" if there's none

Proposed translation: insert your translation proposal

Reason: insert the reason for the change or "new language" if there was no previous translation
