name: Localization
description: File a new translation or a correction for an existing one
title: Death message localization for [lang-tag]
labels: localization
assignees: Crystal-Spider

body:
- type: input
  attributes:
    label: Language
    description: English name of the language for which you want to provide a translation
  validations:
    required: true
- type: input
  attributes:
    label: Current translation
    description: Current translation for that language or "-" if there's none
  validations:
    required: true
- type: input
  attributes:
    label: Proposed translation
    description: Insert your translation proposal
  validations:
    required: true
- type: input
  attributes:
    label: Reason
    description: Insert the reason for the change or "new language" if there was no previous translation
  validations:
    required: true
