name: Pull Request Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested] 

jobs:
  call-analyze-workflow:
    uses: crystal-nest/.github/.github/workflows/analyze.yml@main
    secrets: inherit 
